src/ca377/ca377/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('parkatdcu/',include(('parkatdcu.urls','parkatdcu'),namespace='parkatdcu')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_SUFFIX, document_root=settings.STATIC_ROOT)

src/ca377/parkatdcu/urls.py
from django.urls import path

from . import views

urlpatterns = [
   path('',views.index,name='index'),
   path('carparks/',views.carparks,name='carparks'),
]

src/ca377/parkatdcu/models.py
from django.db import models

# Create your models here.
class Campus(models.Model):
   campus_id = models.IntegerField(primary_key=True)
   name = models.CharField(max_length=100)
   open_time = models.IntegerField(default=7)
   close_time = models.IntegerField(default=21)
   location = models.URLField(max_length=1000, default="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d8004.010781876666!2d-6.262383902137647!3d53.386087299134914!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48670e1b2f9d5d03%3A0x12bb45984107c2a8!2sDublin%20City%20University!5e0!3m2!1sen!2sie!4v1638359746906!5m2!1sen!2sie")

   def __str__(self):
      return self.name

class Carpark(models.Model):
   carpark_id = models.IntegerField(primary_key=True)
   name = models.CharField(max_length=100)
   campus_id = models.ForeignKey(Campus,on_delete = models.CASCADE)
   spaces = models.IntegerField()
   disabled_spaces = models.IntegerField()
   paid_parking = models.CharField(max_length=10, default="Yes")

   def __str__(self):
      return self.name

src/ca377/parkatdcu/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from . models import Campus, Carpark
import requests, datetime
import json

# Create your views here.
def index(request):
    context = {
        "campuses" : Campus.objects.all()
    }
    return render(request,"parkatdcu/index.html",context)

def carparks(request):
    context = {}
    webservice_base_url = "http://mbezbradica.pythonanywhere.com/carparks/"

    # Sets campus_name to selected campus
    campus_name = request.GET['campus']

    try:
        campus = Campus.objects.get(name__iexact=campus_name)
    except Campus.DoesNotExist:
        return HttpResponse('<h1>No such campus</h1>')

    # Checks if campus is open based on opening and closing times in database compared to now
    campus_open = False

    weekday = datetime.datetime.today().weekday()
    hour = datetime.datetime.today().hour

    # Also checks if weekday
    if  weekday < 5 and hour > campus.open_time and hour < campus.close_time:
        campus_open = True

    carparks = Carpark.objects.filter(campus_id=campus)

    # Sets up info for each carpark in selected campus
    carpark_info = []
    for carpark in carparks:

        webservice_url = webservice_base_url + carpark.name

        realtime_info = requests.get(webservice_url).json()

        # This variable is used for colour coding the available spaces part of the table in carparks.html
        availability_status = ""

        if 'spaces_available' in realtime_info:
            spaces_available = realtime_info['spaces_available']
            if (spaces_available/carpark.spaces)*100 <= 10:
                availability_status = "table-danger"
            elif (spaces_available/carpark.spaces)*100 <= 20:
                availability_status = "table-warning"
            else:
                availability_status = "table-success"
        else:
            spaces_available = 'not available'

        carpark_info.append({
                             'name': carpark.name,
                             'spaces': carpark.spaces,
                             'disabled_spaces': carpark.disabled_spaces,
                             'paid_parking': carpark.paid_parking,
                             'spaces_available': spaces_available,
                             'availability_status' : availability_status,
                             }
                            )

    context['campus'] = campus
    context['campus_name'] = campus_name
    context['campuses'] = Campus.objects.all()
    context['campus_map'] = campus.location
    context['campus_open'] = campus_open
    context['carparks'] = carpark_info

    return render(request,"parkatdcu/carparks.html",context)

src/ca377/parkatdcu/templates/parkatdcu/base.html
{% load static %}
<!--This file serves as a base for other html files-->
<head>
<!--Linking Bootstrap 5-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<!--Linking my own css file-->
<link href="{% static 'parkatdcu/style.css' %}" rel="stylesheet" type="text/css" >
<title>Park At DCU</title>
</head>

<body id="text-orange">
<!--Centers content of site-->
<div class="container p-5 pt-0 text-grey text-center">
    <div>
        <!--A basic navbar with links to the DCU website-->
        <nav class="navbar navbar-expand bg-dark navbar-dark ps-5">
            <!--DCU logo on navbar links to DCU website-->
            <div>
                <a href="https://www.dcu.ie/"><img src="{% static 'parkatdcu/images/dcu_logo_red.png' %}" alt="Logo"/></a>
            </div>
            <!--Links to Parkatdcu index page and DCU website-->
            <div>
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="https://www.dcu.ie/attendingdcu">DCU</a></li>
                    <li class="nav-item"><a class="nav-link" href="https://www.dcu.ie/phonebook?find-staff=People...">Contact</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'parkatdcu:index' %}">ParkAtDCU</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Campuses</a>
                        <!--A dropdown menu containing links to the campuses covered by Parkatdcu-->
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'parkatdcu:carparks' %}?campus=Glasnevin">Glasnevin</a></li>
                            <li><a href="{% url 'parkatdcu:carparks' %}?campus=All Hallows">All Hallows</a></li>
                            <li><a href="{% url 'parkatdcu:carparks' %}?campus=St. Pats">St. Pats</a></li>
                            <li><a href="{% url 'parkatdcu:carparks' %}?campus=DCU Alpha">DCU Alpha</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
{% block content %}
<!--Default page content-->
<div class="container-fluid">
    <br><br><br><br><h1>Welcome to ParkAtDCU</h1><br>
</div>
{% endblock %}
</div>
</body>

src/ca377/parkatdcu/templates/parkatdcu/carparks.html
{% extends './base.html' %}

{% block content %}
<div class="container mt-5">
<div class="container">
<h1>{{ campus }}</h1>
<!--Checks if the campus is open at the current time-->
{% if campus_open %}
<h3 class="text-success">Campus is open</h3>
{% else %}
<h3 class="text-danger">Campus is closed</h3>
{% endif %}
</div>
<div class="container mt-3">
<!--Checks if there are any carparks to display-->
{% if carparks %}
<!--Carpark information is displayed in a table-->
<table class="table table-striped">
    <thead>
        <tr class="table-dark">
            <th>Carpark Name</th>
            <th>Total Spaces</th>
            <th>Available Spaces</th>
            <th>Disability Spaces</th>
            <th>Paid Parking</th>
        </tr>
    </thead>
    <tbody>
    {% for carpark in carparks %}
        <tr>
            <td class="table-dark">{{carpark.name}}</td> 
            <td>{{carpark.spaces}}</td>
            <!--Available spaces is colour-coded based on percentage of spaces available-->
            <td class={{carpark.availability_status}}>{{carpark.spaces_available}}</td>
            <td>{{carpark.disabled_spaces}}</td>
            <td>{{carpark.paid_parking}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h3 class="display-4">No carparks found</h3>
{% endif %}
<!--An easy way to return to index page-->
<a href="{% url 'parkatdcu:index' %}">Home</a>
</div>
<!--An embedded map of the campus being viewed-->
<div>
    <!--Map is selected from database-->
    <iframe src="{{campus_map}}" width="600" height="450" style="border:0;" loading="lazy" allowfullscreen></iframe>
</div>
</div>
{% endblock %}

src/ca377/parkatdcu/templates/parkatdcu/index.html
{% extends './base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <br><br><h1>Welcome to ParkAtDCU</h1><br>
</div>
<div>
    <h3 class="display-5">Check the availability of parking across Dublin City University's campuses</h3><br>
</div>
<div class="container">
    <!--This is a select menu to pick which campus to view-->
    <form action="{% url 'parkatdcu:carparks' %}" method="get">
        <label class="form-label text-orange">Select Campus</label>
        <!--The java in this line submits what the user selects as they select it; no need for a confirm button-->
        <select class="form-select" onchange="this.form.submit()" name="campus" value="">
        <!--A default null value tell the user what to do-->
        <option disabled selected value> -- Select a Campus -- </option>
        <!--For-loop lists campuses from databse as options-->
        {% for campus in campuses %}
            <option value="{{campus}}">{{campus}}</option>
        {% endfor %}
        </select>
    </form>
</div>
<br>
<br>
<!--A carousel displaying a image for each campus, mainly gotten from https://www.w3schools.com/bootstrap5/bootstrap_carousel.php-->
<div id="demo" class="carousel slide container text-center" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="3" aria-label="Slide 4"></button>
    </div>

    <div class="carousel-inner">
        <div class="carousel-item active">
            <a href="{% url 'parkatdcu:carparks' %}?campus=Glasnevin"><img src="{% static 'parkatdcu/images/glasnevin.png' %}" alt="Glasnevin" class="d-block w-100"></a>
            <div class="carousel-caption">
                <h3>Glasnevin</h3>
            </div>
        </div>
        <div class="carousel-item">
            <a href="{% url 'parkatdcu:carparks' %}?campus=All Hallows"><img src="{% static 'parkatdcu/images/allhallows.png' %}" alt="All Hallows" class="d-block w-100"></a>
            <div class="carousel-caption">
                <h3>All Hallows</h3>
            </div>
        </div>
        <div class="carousel-item">
            <a href="{% url 'parkatdcu:carparks' %}?campus=St. Pats"><img src="{% static 'parkatdcu/images/stpats.png' %}" alt="St. Patricks" class="d-block w-100"></a>
            <div class="carousel-caption">
                <h3>St. Pats</h3>
            </div>
        </div>
        <div class="carousel-item">
            <a href="{% url 'parkatdcu:carparks' %}?campus=DCU Alpha"><img src="{% static 'parkatdcu/images/dcualpha.png' %}" alt="DCU Alpha" class="d-block w-100"></a>
            <div class="carousel-caption">
                <h3>DCU Alpha</h3>
            </div>
        </div>
    </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
          <span class="carousel-control-prev-icon"></span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
          <span class="carousel-control-next-icon"></span>
      </button>
</div>


{% endblock %}